version: 0.1.{build}

os: Windows Server 2012

environment:
  filecryptkey:
    secure: O+Xh3uOvePVVWMIFI9OW0O6Oew0piFeAs5sS7Oj693c=

cache:
  - packages -> **\packages.config
  - bld\sitecore.zip -> bld\DownloadSitecore.ps1 
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - nuget install secure-file -ExcludeVersion  
  - secure-file\tools\secure-file -decrypt lib\sitecore.zip.enc -secret %filecryptkey%
  - choco install gitversion.portable -y

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'  


# Build

platform: Any CPU
configuration: Release

before_build:
  - ps: |
      $shell = new-object -com shell.application
      $src = (Join-Path $PWD "lib\sitecore.zip")
      $dst = (Join-Path $PWD "src\website\bin")
      If((Test-Path $dst) -eq $false) {
          md $dst
      }
      
      $zip = $shell.NameSpace($src)
      $target = $shell.NameSpace($dst)
      Write-Host $target
      foreach($item in $zip.items())
      {
        $target.copyhere($item)
      }
  - ps: gitversion /l console /output buildserver /updateassemblyinfo
  - cmd: "echo Building version: %GitVersion_NuGetVersion% by %appveyor_build_version%"
  - cmd: "nuget restore"

build:
  project: SitecoreCodeBasedSourceFields.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  verbosity: detailed

after_build:
  - cmd: ECHO nuget pack src\SitecoreCodeSourceFields\SitecoreCodeBasedSourceFields.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack src\SitecoreCodeSourceFields\SitecoreCodeBasedSourceFields.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "SitecoreCodeBasedSourceFields.%GitVersion_NuGetVersion%.nupkg"
  
# Test
test:
  assemblies:
    - SitecoreCodeSourceFields.UnitTests.dll

# Artifacts
artifacts:
  - path: out\*.nupkg
  - path: SitecoreCodeBasedSourceFields.%GitVersion_NuGetVersion%.nupkg

# Deploy

# Notification
