version: 0.1.{build}

os: Windows Server 2012

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  filecryptkey:
    secure: O+Xh3uOvePVVWMIFI9OW0O6Oew0piFeAs5sS7Oj693c=

cache:
  - packages -> **\packages.config
  - bld

install:
  - nuget install secure-file -ExcludeVersion  
  - secure-file\tools\secure-file -decrypt lib\sitecore.zip.enc -secret %filecryptkey%

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'  


# Build

platform: Any CPU
configuration: Release

before_build:
  - ps: |
      $shell = new-object -com shell.application
      $src = (Join-Path $PWD "lib\sitecore.zip")
      $dst = (Join-Path $PWD "src\website\bin")
      If((Test-Path $dst) -eq $false) {
          md $dst
      }
      
      $zip = $shell.NameSpace($src)
      $target = $shell.NameSpace($dst)
      Write-Host $target
      foreach($item in $zip.items())
      {
        $target.copyhere($item)
      }
  - cmd: "echo Building version:%appveyor_build_version%"
  - cmd: "nuget restore"

build:
  project: SitecoreCodeBasedSourceFields.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  verbosity: detailed
  
# Test
test:
  assemblies:
    - SitecoreCodeSourceFields.UnitTests.dll

# Artifacts
artifacts:
  - path: out\*.nupkg

# Deploy

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Notification
