assembly-versioning-scheme: 'MajorMinorPatch'
mode: ContinuousDelivery
branches: 
  master:
    tag: ""
    prevent-increment-of-merged-branch-version: true
  development:
    tag: beta
  features?[/-]:
    tag: alpha-{BranchName}
    increment: Minor
  (pull|pull\-requests|pr)[/-]:
    tag: PullRequest
    increment: Minor
    track-merge-target: true
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
  
